Modifications:
Run codeclimate only on files changed
Change logic of Pass / Fail of action

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -1,5 +1,5 @@
 name: "Code Climate Standalone"
-author: "Sean Erswell-Liljefelt"
+author: "Karan Shah & Sean Erswell-Liljefelt"
 description: "Runs a detached version of CodeClimate which reports only in the workflow and does not require the CodeClimate Service"
 branding:
   color: gray-dark
@@ -75,6 +75,11 @@ runs:
           echo "::warning::No configuration found, using Code Climate's default configuration"
         fi
 
+        git switch $GITHUB_HEAD_REF
+        git switch ${GITHUB_REF##*/}
+        files_changed=$(git --no-pager diff --name-only $GITHUB_HEAD_REF..${GITHUB_REF##*/})
+        files_changed="${files_changed//$'\n'/ ./}"
+
         # Run once for JSON output
         echo "#### INITIAL RUN ####"
         docker run \
@@ -82,7 +87,7 @@ runs:
           --volume "$PWD":/code \
           --volume /var/run/docker.sock:/var/run/docker.sock \
           --volume /tmp/cc:/tmp/cc \
-          codeclimate/codeclimate analyze -f json > raw.json
+          --entrypoint /bin/sh codeclimate/codeclimate -c "cd /code && /usr/src/app/bin/codeclimate prepare > /dev/null && /usr/src/app/bin/codeclimate analyze $files_changed -f json" > raw.json
 
         # Strip the json to only issues
         jq -c 'map(select(.type | test("issue"; "i")))' raw.json > codeclimate-report.json
@@ -102,9 +107,9 @@ runs:
         echo "::set-output name=major::$TOTAL_MAJOR"
         echo "::set-output name=critical::$TOTAL_CRITICAL"
         echo "::set-output name=blocker::$TOTAL_BLOCKER"
+        echo "::set-output name=files_changed::$files_changed"
 
-    # Second run purely to get the readable HTML report. The second run is much faster than the first
-    # as it does not need to redownload the images already pulled by the first run
+    # Second run purely to get the readable HTML report. The second run is much faster than the first as it does not need to redownload the images already pulled by the first run
     - name: Generate HTML Report
       shell: bash
       env:
@@ -126,11 +131,11 @@ runs:
           # Run for HTML output
           echo "#### GENERATING HTML VERSION ####"
           docker run \
-            --env CODECLIMATE_CODE="$PWD" \
-            --volume "$PWD":/code \
-            --volume /var/run/docker.sock:/var/run/docker.sock \
-            --volume /tmp/cc:/tmp/cc \
-            codeclimate/codeclimate analyze -f html > codeclimate-report.html
+          --env CODECLIMATE_CODE="$PWD" \
+          --volume "$PWD":/code \
+          --volume /var/run/docker.sock:/var/run/docker.sock \
+          --volume /tmp/cc:/tmp/cc \
+          --entrypoint /bin/sh codeclimate/codeclimate -c "cd /code && /usr/src/app/bin/codeclimate prepare > /dev/null && /usr/src/app/bin/codeclimate analyze ${{ steps.cc.outputs.files_changed }} -f html" > codeclimate-report.html
         else
           echo "HTML REPORT not requested, skipping..."
         fi
@@ -154,9 +159,11 @@ runs:
         echo "critical: ${{ steps.cc.outputs.critical }} allowed: $CC_CRITICAL_ALLOWED"
         echo "blocker: ${{ steps.cc.outputs.blocker }} allowed: $CC_BLOCKERS_ALLOWED"
 
-        # Pass or Fail the job depending on the findings / inputs
-        if [ ${{ steps.cc.outputs.blocker }} -gt "$CC_BLOCKERS_ALLOWED" ] || [ ${{ steps.cc.outputs.critical }} -gt "$CC_CRITICAL_ALLOWED" ] || [ ${{ steps.cc.outputs.major }} -gt "$CC_MAJOR_ALLOWED" ] || [ ${{ steps.cc.outputs.minor }} -gt "$CC_MINOR_ALLOWED" ] || [ ${{ steps.cc.outputs.info }} -gt "$CC_INFO_ALLOWED" ]; then
-          exit 1
+         # Pass or Fail the job depending on the findings / inputs
+        if [ ${{ steps.cc.outputs.blocker }} -gt "$CC_BLOCKERS_ALLOWED" ] || [ ${{ steps.cc.outputs.critical }} -gt "$CC_CRITICAL_ALLOWED" ] || [ ${{ steps.cc.outputs.major }} -gt "$CC_MAJOR_ALLOWED" ]; then
+          if [ ${{ steps.cc.outputs.minor }} -gt "$CC_MINOR_ALLOWED" ] || [ ${{ steps.cc.outputs.info }} -gt "$CC_INFO_ALLOWED" ]; then
+            exit 1
+          fi
         else
           exit 0
         fi
